version: '3'

services:
  nginx:
    build:
        context: .
        dockerfile: Dockerfile_nginx
    image: nginx
    ports:
      - 8084:8084
    container_name: test-nginx
    network_mode: "host"
